spring:
  datasource:
    platform: postgres
    url: ${db-url:jdbc:postgresql://localhost:5432/auto3n}
    username: ${db-user:auto3n}
    password: ${db-pass:auto3n2pass}
    driverClassName: org.postgresql.Driver
    auto-commit: false