spring:
#  jpa:
#    hibernate:
#      ddl-auto: update
  datasource:
    platform: postgres
    url: ${db-url:jdbc:postgresql://192.168.1.33:5432/rest}
    username: ${db-user:rest}
    password: ${db-pass:rest}
    driverClassName: org.postgresql.Driver
    auto-commit: false
liquibase:
  change-log: classpath:/db/changelog/liquibase-main.xml
  enabled: true
server:
  contextPath: /pelican
  port: 8088